[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pymongo>=4.13.2",
    "python-socketio>=5.13.0",
    "uvicorn>=0.35.0",
]
